name: Python uv CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-slim
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}
      - run: uv sync --dev --locked
      - run: uv run ty check
      - run: uv run isort --check .
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run coverage run --module pytest
      - run: uv run coverage html
      - run: uv run coverage lcov
      - run: uv run coverage report
      - run: uv run coverage xml
      - if: matrix.python == '3.13'
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          path: coverage/
          name: coverage-report

  quality:
    runs-on: ubuntu-slim
    needs:
      - test
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: "0"
      - uses: actions/download-artifact@v7
        with:
          name: coverage-report
          path: coverage/
      - uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  mutation:
    runs-on: ubuntu-latest
    needs:
      - test
    outputs:
      report: ${{ steps.mutation.outputs.report }}
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: echo "report=$(uv run python ./bin/mutation.py)" >> "$GITHUB_OUTPUT"
        id: mutation
      - uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          path: ${{ steps.mutation.outputs.report }}
          name: mutation-report

  build:
    runs-on: ubuntu-slim
    needs:
      - test
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: uv version ${{ github.ref_name }}
      - run: uv build
      - uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          path: dist/
          name: package

  deploy-pypi:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pydantic-json-patch/
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: package
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1

  deploy-gh-release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - build
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: package
          path: dist/
      - run: gh release upload ${{ github.ref_name }} dist/*
        env:
          GH_TOKEN: ${{ github.token }}

  smoke-test:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - deploy-pypi
    runs-on: ubuntu-slim
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - uses: Wandalen/wretry.action@v3
        with:
          attempt_delay: 60000
          attempt_limit: 10
          command: pip install "pydantic-json-patch==${VERSION#v}"
        env:
          VERSION: ${{ github.ref_name }}
      - run: python3 -c 'from pydantic_json_patch import __version__;print(__version__)'
